version: "3"

services:
  movie-app:
    build: .
    restart: on-failure
    networks:
      - sonarnet
    ports:
      - "8000:8000"
    expose:
      - 8000

  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - sonardb
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://sonardb/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  sonardb:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  mariadb:
  postgresql:
  postgresql_data:
